name: Build

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller -F main.py
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        token: ${{ secrets.TOKEN }}
